### ISSUE TITLE
Lesson 3 task 8 Character Escaping

### ISSUE THREAD

**Issue by mwinchester** [JetBrains/pycharm-courses#10]
You can put in code that gives you what appears to be the correct text on screen, but are told the wrong text is being displayed.

dont_worry = "Don't worry about apostrophes"
print(dont_worry)
print("The name of this ice-cream is \"Sweeet\"")
print("The name of this ice-cream is\n \"Sweet\'n\'Tasty\"")

I have played with different or no spacing around the \n, and I have tried it both with the default single quotes or clicking the lightbulb to switch to double quotes. This is deeply frustrating.

**Comment by ktisha** [comment]
Thanks for the feedback! We'll update tests for this task soon.
