### ISSUE TITLE
tested_code is missing from pycharm-courses/unit_testing_course/lesson2/task2/

### ISSUE THREAD

**Issue by sudopluto** [JetBrains/pycharm-courses#13]
the lesson imports "tested_code", but tested_code is not found
![image](https://cloud.githubusercontent.com/assets/9754192/17820726/341a4afc-661c-11e6-887f-9de43f8c1452.png)

**Comment by lancelote** [comment]
Hi @sudopluto 

Not sure if it is a bug or the course author expect students to implement `tested_code` by themself but here the code I wrote to pass this task:

```python
# tested_code.py in the same directory as comparison_assertions.py
import random


def random_not_42():
    return random.choice([i for i in range(100) if i != 42])


def find_foo(test_string):
    return object() if 'foo' in test_string else None


def random_float_between_inclusive(start, end):
    return random.uniform(start, end)


def random_float_between_noninclusive(start, end):
    epsilon = 1/10**16
    return random.uniform(start + epsilon, end - epsilon)
```

Hope it helps.

**Comment by tszebeni** [comment]
In git history the file indeed has been removed, but lesson still relies on that
