### ISSUE TITLE
PyCharm wrongly renders text for Introduction to Python - lesson 9 - task 1 and 3

### ISSUE THREAD

**Issue by lancelote** [JetBrains/pycharm-courses#25]
### Task 1

<img width="413" alt="wrong" src="https://user-images.githubusercontent.com/2500320/28997615-9078915e-7a21-11e7-802a-f9866580b39e.png">

Should be:

>import the module `my_module` and use the `hello_world` function.

### Task 3

<img width="418" alt="wrong2" src="https://user-images.githubusercontent.com/2500320/28997647-5243bb38-7a22-11e7-8238-82375786b92e.png">

Should be:

> Import `hello_world` function from `my_module`. Check the difference with task1.

**Comment by Samsomyajit** [comment]
assign me @Samsomyajit this issue I am doing it

**Comment by Samsomyajit** [comment]
> ### Task 1
> <img alt="wrong" width="413" src="https://user-images.githubusercontent.com/2500320/28997615-9078915e-7a21-11e7-802a-f9866580b39e.png">
> 
> Should be:
> 
> > import the module `my_module` and use the `hello_world` function.
> 
> ### Task 3
> <img alt="wrong2" width="418" src="https://user-images.githubusercontent.com/2500320/28997647-5243bb38-7a22-11e7-8238-82375786b92e.png">
> 
> Should be:
> 
> > Import `hello_world` function from `my_module`. Check the difference with task1.

I have seen the problem you stated but it seems the documentation error has been removed as it seems. but if you can rather specify your problem with a bit details it will help

**Comment by lancelote** [comment]
Hi @Samsomyajit, thank you for looking into it. Looks like the problem was since gone.
