### ISSUE TITLE
pycham remote access Process finished with exit code -1 and no Trackback

### ISSUE THREAD

**Issue by jamesben6688** [JetBrains/pycharm-courses#26]
I am using pycharm professional 2017.2 to access my remote server to run a deep convolution network. The process is a resnet50 network and will last for a long time. Each time before I go to bed, everything works fine. However, when I get up the next day and see the pycharm console, it says Process finished with exit code -1, and there is not any Traceback. But when I run that process again, everything works fine. Is this a bug in pycharm or I have to do some settings with pycharm?

The operating system on that server is ubuntu 16.04 and python interpreter is python 3.5.2. I was running a resnet50 with keras 2.0.8 and tensorflow-gpu 1.0.0.

**Comment by ktisha** [comment]
Hi @jamesben6688 , please, file this issue in PyCharm tracker -- https://youtrack.jetbrains.com/issues/PY
