### ISSUE TITLE
Cannot select Conda virtual environment as python interpreter

### ISSUE THREAD

**Issue by okdolly-001** [JetBrains/pycharm-courses#31]
<img width="952" alt="screen shot 2018-04-05 at 7 06 55 pm" src="https://user-images.githubusercontent.com/18589970/38400353-a0dbc168-3904-11e8-9aa1-77ab7903cdd9.png">
My conda environment is called PY36,however,I cannot click "ok." It seems like I can only choose a file,but which file?

My base interpreter is Python 3.6.2 (/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6) 

<img width="988" alt="screen shot 2018-04-05 at 7 08 55 pm" src="https://user-images.githubusercontent.com/18589970/38400416-d83df50e-3904-11e8-8b92-658c9795185d.png">

**Comment by ktisha** [comment]
Hi @okdolly, 

please, choose /anaconda/envs/PY36/bin/python as an interpreter in this dialog.
