### ISSUE TITLE
Pycharm shows strange code of Jupyter 

### ISSUE THREAD

**Issue by grimwoo** [JetBrains/pycharm-courses#34]
I used the pro version (2019.07) of pycharm, and I might have installed all the module needed.
But when I open the try.ipynb file, I shows this stuff (figure attached below). Could anyone help me?

![Jupyter](https://user-images.githubusercontent.com/49429496/65296405-ec724580-db96-11e9-9b07-79c2a65b3925.png)
![interpreter](https://user-images.githubusercontent.com/49429496/65296406-ec724580-db96-11e9-84ac-01fa132ae734.png)

**Comment by lancelote** [comment]
Make sure Jupyter plugin is enabled

<img width="1013" alt="Screen Shot 2019-09-20 at 11 55 28" src="https://user-images.githubusercontent.com/2500320/65313766-994fc100-db9d-11e9-8c80-6847e49d253a.png">

There's a public PyCharm bug tracker https://youtrack.jetbrains.com/issues/PY, it is better to report such problems there or directly to pycharm-support@jetbrains.com

**Comment by grimwoo** [comment]
@lancelote Hi, thanks for your suggestion. But I've already have the "Plugins“

![image](https://user-images.githubusercontent.com/49429496/65381215-81a04600-dd1f-11e9-8ee8-8ce3905ec021.png)

**Comment by lancelote** [comment]
@grimwoo Send the `idea.log` from **Help | Show Log in ...** to PyCharm support at pycharm-support@jetbrains.com Perhaps there're something relevant in it.

**Comment by grimwoo** [comment]
@lancelote Thanks!

**Comment by grimwoo** [comment]
Hi, I deleted the ".ipyng" in othors and added it in Jupyter Notebook in "Settings | Editor | File Types ". And then I closed the current ".ipynb" file and re-open it, and it worked! Many thanks to you and the support team of Pycharm!
