### ISSUE TITLE
Solution incorrect

### ISSUE THREAD

**Issue by BjhDaddio** [JetBrains/pycharm-courses#7]
The "correct solution" returns:
[0, 1, 1, 2, 3, 5, 8]

But, by definition, and by the problem statement, the first two Fibonacci numbers are 1, 1.

The "correct solution" should be:
[1, 1, 2, 3, 5, 8]

**Comment by iandouglas** [comment]
The Fibonacci sequence begins with a 0.

**Comment by BjhDaddio** [comment]
My bad.  You are right!

**Comment by ktisha** [comment]
Thanks for the issue.

Actually, [by definition, the first two numbers in the Fibonacci sequence are either 1 and 1, or 0 and 1, depending on the chosen starting point of the sequence](https://en.wikipedia.org/wiki/Fibonacci_number)

We've updated task and 'correct solution' to be less confusing.
