### ISSUE TITLE
Question on Lession 7, task 3

### ISSUE THREAD

**Issue by jimmysun** [JetBrains/pycharm-courses#8]
Hi,

The original .py file and .py answer file is shown [here](https://github.com/JetBrains/pycharm-courses/tree/master/introduction_course/lesson7/task3)
I have seen issue[#7](https://github.com/JetBrains/pycharm-courses/issues/7) on topic on the task, but I feel sorry that it still exists now. 

I have downloaded a **education version** of PyCharm hours before, and the version is **2.0.4**.

I have seen the task description on the right saying
> In the Fibonacci sequence, the **first two numbers are 1 and 1**, and each subsequent number is the sum of the previous two. Write a function that returns **a list of the numbers** of the Fibonacci series.

It takes me almost an hour on this issue (I majored in computer science and I knew the basic python grammar before). I got the wrong answer all the time, before I find this repo by Google.

Obviously, the answer you give does **not** satisfy the description. What is more, in traditional  Fibonacci problems, the input value _n_ is not used as the maximum number in the sequence -- it should be the total number of resulting series, as in the task description.

Hope something should be done to **avoid wasting the time of others**. (Maybe something wrong with the given correct answer, or, maybe you should change the description)
Best regards.

**Comment by ktisha** [comment]
Thanks a lot for your feedback! We'll definitely update this task to make it less confusing.
